inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Performance/RedundantBlockCall:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

LineLength:
  Max: 100

Metrics:
  Enabled: false

Naming/FileName:
  Exclude:
    - Appraisals

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/AccessModifierDeclarations:
  Enabled: false
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/BlockDelimiters:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  Exclude:
    - Rakefile
Style/IfUnlessModifier:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/Next:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'
Style/RaiseArgs:
  EnforcedStyle: compact
Style/SignalException:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/FrozenStringLiteralComment:
  Exclude:
    - "gemfiles/*.gemfile"
    - "Appraisals"